export const LIST_PROJECTS_API = 'LIST_PROJECTS_API';
export const ADD_PROJECT_API = 'ADD_PROJECT_API';
export const UPDATE_PROJECT_API = 'UPDATE_PROJECT_API';
export const DELETE_PROJECT_API = 'DELETE_PROJECT_API';

export const LIST_TASKS_API = 'LIST_TASKS_API';
export const FINISH_TASK_API = 'FINISH_TASK_API';
export const UPDATE_TASK_API = 'UPDATE_TASK_API';
export const DELETE_TASK_API = 'DELETE_TASK_API';


